import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import FloatingMenu from "@/components/FloatingMenu"
import Footer from "@/components/Footer"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} min-h-full flex flex-col scroll-smooth`} data-scroll-behavior="smooth">
      <body className="min-h-full flex flex-col bg-background">
        <Navbar/>
        {children}
        <Footer/>
        <FloatingMenu/>
      </body>
    </html>
  );
}
